# -*- mode: ruby -*-

Vagrant.configure("2") do |config|

  config.vm.box = "ol76"
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/vagrant_data"

 
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #

  config.vm.provision "shell", inline: <<-SHELL
    yum update -y
    mv /etc/yum.repos.d/public-yum-ol7.repo /etc/yum.repos.d/public-yum-ol7.repo.bak
    wget -O /etc/yum.repos.d/public-yum-ol7.repo http://yum.oracle.com/public-yum-ol7.repo
    yum install -y yum-utils
    yum-config-manager --enable ol7_developer_php72
    yum install unzip php
    wget http://wordpress.org/latest.zip
    mkdir -p /var/www/html && mv wordpress/ /var/www/html
    
  SHELL
end
