# -*- mode: ruby -*-

require 'yaml'
secrets = YAML.load_file 'secret.yaml'

# $script = <<-SCRIPT
# export NEWPASS="$1"
# SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ol76"
  
  config.vm.provider "virtualbox" do |vb|
   # Display the VirtualBox GUI when booting the machine
   vb.memory = "1024"
  end
  
  config.vm.provision "shell",
    path: "mysql_setup.sh",
    args: [secrets['newpass'], secrets['wppass']]
  

end

